# 예외처리(exception handing)
### 프로그램 오류
- 발생시점에 따라 컴파일에러(compile-time error), 런타임에러(runtime error)로 나눌 수 있다
  - 컴파일 에러 : 컴파일할 때 발생하는 에러
  - 런타임 에러 : 프로그램의 실행도중 발생하는 에러
  - 논리적 에러 : 컴파일도 잘 되고 실행도 잘 되지만 의도한 것과 다르게 동작할 때

<br>

- 자바는 실행 시 발생할 수 있는 오류를 '에러', '예외' 두 가지로 구분했다
  - 에러 : 메모리 부족(OutOfMemoryError)이나 스택오버플로우(StackOverflowError)와 같이 발생하면 복구할 수 없는 심각한 오류
  - 예외 :발생하더라도 수습될 수 있는 비교적 덜 심각한 것

<br><br>
- 에러 : 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
- 예외 : 프로그램 코드에 의해서 수습 될 수 있는 다소 미약한 오류

<br><br>


모든 예외의 최고 조상은 Exception클래스<br>상속계층도를 Exception클래스부터 도색화하는 것은 책415p참고

<br><br>
예외클래스들은 다음과 같이 두 그룹으로 나눠질 수 있다
1. Exception클래스와 그 자손들
2. RuntimeException클래스와 그 자손들

<br>

- Exception클래스들은 주로 외부의 영향으로 발생할 수 있는 것들로, 프로그램의 사용자들 동작에 의해서 발생하는 경우가 많다
- RuntimeException클래스들은 주로 프로그래머의 실수에 의해서 발생

<br><br>

### 예외처리하기 try-catch문

프로그램의 실행도중 발생하는 예외는 프로그래머가 이에 대한 처리를 미리 해줘야한다<br>
<br>예외처리의 목적은 예외의 발생으로 인한 실행 중인 프로그램의 갑작스런 비정상 종료를 막고 정상적인 실행상태를 유지할 수 있도록 하는 것


- 예외처리
  - 정의 : 프로그램 실행 시 발생할 수 있는 예외에 대비한 코드를 작성하는 것
  - 목적 : 프로그램의 비정상 종료를 막고 정상적인 실행상태를 유지하는 것

<br>
예외를 처리하기 위해서 try-catch문을 사용한다<br>
try{<br>//예외가 발생할 가능성이 있는 문장을 넣음<br>} catch (Exception1 e1) {<br>//Exception1이 발생했을 경우 이를 처리하기 위한 문장<br>} catch (Exception2 e2) {<br>}


<br><br>

catch블럭의 괄호 내에 선언된 변수는 catch블럭 내에서만 유효하기때문에 위의 모든 catch블럭에 참조변수 'e'하나만을 사용해도 된다

<br><br>

### try-catch문에서의 흐름

- try블럭 내에서 예외가 발생한 경우
    1. 발생한 예외와 일치하는 catch블럭이 있는지 확인한다
    2. 일치하는 catch블럭을 찾게 되면 그 catch블럭 내의 문장들을 수행하고 전체try-catch문을 빠져나가서 그 다음 문장을 계속해서 수행, 만약 일치하는 catch 블럭을 찾지 못하면 예외는 처리되지 못한다

- try블럭 내에서 예외가 발생하지 않은 경우
  1. catch블럭을 거치지 않고 전체 try-catch문을 빠져나가서 수행을 계속한다

<br><br>

### 예외의 발생과 catch블럭
- 모든 예외클래스는 Exception클래스의 자손이므로, catch블럭의 괄호()에 Exception클래스타입의 참조변수를 선언해놓으면 어떤 종류의 예외가 발생하더라도 이 catch블럭에 의해서 처리된다

- printStackTrace() : 예외발생 당시의 호출스택(Call Stack)에 있었던 메서드의 정보와 예외 메세지를 화면에 출력한다
- getMessage() : 발생한 예외클래스의 인스턴스에 저장된 메세지를 얻을 수 있다


<br><br>

### 예외 발생시키기
- 키워드 throw를 사용해 고의로 예외를 발생시킬 수 있다

1. 먼저 연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 만든 다음<br>- Exception e = new Exception("고의로 발생시킴");
2. 키워드 throw를 이용해서 예외를 발생시킨다<br>throw e;


<br><br>

### 메서드에 예외 선언하기
- 메서드에 예외를 선언하려면 메서드의 선언부에 키워드 throws를 사용하여 메서드 내에서 발생할 수 있는 예외를 적어주면 된다, 예외가 여러 개일 경우에는 쉼표, 로 구분한다


- 예외가 발생한 메서드 내에서 처리가능
- 예외가 발생한 메서드를 호출한 메서드에서 처리가능
- 또는 두 메서드가 예외처리를 분담가능

<br><br>

### finally블럭